### ISSUE TITLE
Check the plotting examples that use numpy

### ISSUE THREAD

**Issue by dythya** [SimPyClassic/SimPyClassic#27]

**Comment by dythya** [comment]
Example program
on 3.7 NameError: name 'CanvasText' is not defined

# Prog1.py
from SimPy.SimPlot import *
plt=SimPlot()
plt.plotLine([[0,0],[1,1],[2,4],[3,9]])
plt.mainloop()

**Comment by dythya** [comment]
Tried installing canvas on python 3.

pip install canvas  # 3.6 
>>> import canvas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karen/.virtualenvs/SimPyClassic/lib/python3.6/site-packages/canvas.py", line 5, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'
>>> quit

Canvas https://pypi.python.org/pypi/canvas - does not have CanvasText as a thing.  So not sure what Canvas was being used. it is just a simply interface to matplot lib so should be able to just drop that in.
@johnguant  one of us can do it.

**Comment by dythya** [comment]
SimPlot now works on Python 3.
